### ISSUE TITLE
dwidenoise not working on WS

### ISSUE THREAD

**Issue by finnlennartsson** [HIIM-PERINEDO/zagreb_dhcp#33]
Consistent freezing of dwidenoise when running on PMR data.

Works for BATMAN tutorial data. PMR data works on Finn's laptop.

Memory leak?

**Comment by Dlasic7** [comment]
The problem is that the dwidenoise command (as well as mrdegibbs and dwifslpreproc) uses all available cores for computation and drives them to 100% core usage which then leads to overheating (>100 celsius, compared to normal 60-70) of the CPU and subsequent hardware shutdown of the computer. Because of this the dwidenoise , mrdegibbs and dwifslpreproc commands should be run with the option -nthreads 8 ,  when added solves the problem.
The problem can be verified by monitoring PC resources with "System monitor" and tracking the CPU temperature with "watch -n1 sensors".
