### ISSUE TITLE
Problem with registration- peripheral parts of the brain not segmented

### ISSUE THREAD

**Issue by Dlasic7** [HIIM-PERINEDO/zagreb_dhcp#40]
![screenshot](https://user-images.githubusercontent.com/64853467/235366148-45783025-638c-4e22-ae06-975de4810c90.png)

**Comment by Dlasic7** [comment]
Problem was that the dhollander_2tt_wm was not registered to the diffusion space so there was a discepancy in brain tissue between the files:
derivatives/dMRI_csd/sub-sID/ses-ssID/csd/dhollander/csd_dhollander_wm_2tt.mif.gz &&
derivatives/dMRI_registration/sub-sID/ses-ssID/dwi/act/neonatal-5TT-M-CRIB/5TT_coreg.mif.gz

Solved by adding to the dMRI_registration(registering 2tt_wm to diffusion space:

`csddir=dwi/csd
csd_wm_2tt_base=`basename $csd_wm_2tt .mif.gz`
if [ ! -f $csddir/${allLabel}_space-dwi.nii.gz ]; then
    mrtransform $csddir/$csd_wm_2tt_base.mif.gz -linear xfm/sub-${sID}_ses-${ssID}_from-dwi_to-T2w_mrtrix-bbr.mat $csddir/${csd_wm_2tt_base}_space-dwi.nii.gz -inverse -reorient_fod yes
    mrconvert $csddir/${csd_wm_2tt_base}_space-dwi.nii.gz $csddir/${csd_wm_2tt_base}_coreg.mif.gz
fi`

**Comment by Dlasic7** [comment]
![screenshot_solved](https://user-images.githubusercontent.com/64853467/235366483-da58d8dd-a226-4a37-9509-4796197dca19.png)

**Comment by finnlennartsson** [comment]
There is a bit of a mixture between old and new code here. The "new" code tries to use the BIDS conversion of how state which space something is in, i.e. "space-dwi" = diffusion space. Also try to stick with the conventions of how transforms are named and saved (in /xfms) according to the [dHCP 3rd data release](https://biomedia.github.io/dHCP-release-notes/structure.html#image-spaces).

"T2_coreg" comes from the "old" code but means a transformation of T2w into diffusion space, it it would be better to tag this as "space-dwi" instead of "coreg". 

csd will always lives in dwi space and do not need the tag "space-dwi". It could be transformed into T2w space, but a good golden rule is to always stick with the dwi:s in dwi space. (See comment in https://mrtrix.readthedocs.io/en/latest/quantitative_structural_connectivity/act.html#image-registration).

The command
```
if [ ! -f $csddir/${allLabel}_space-dwi.nii.gz ]; then mrtransform $csddir/$csd_wm_2tt_base.mif.gz -linear xfm/sub-${sID}_ses-${ssID}_from-dwi_to-T2w_mrtrix-bbr.mat $csddir/${csd_wm_2tt_base}_space-dwi.nii.gz -inverse -reorient_fod yes mrconvert $csddir/${csd_wm_2tt_base}_space-dwi.nii.gz $csddir/${csd_wm_2tt_base}_coreg.mif.gz fi
```
does not make sense to me. It actually applies the inverse transform "dwi-to-T2w" to "csd", in other words takes something from T2 space into dwi space. Since csd already is in dwi space, it does not make sense.
